# Generated by Django 2.1 on 2018-08-14 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0015_auto_20180130_0013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='forms',
            field=models.ManyToManyField(to='fobi.FormElement'),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='NOINFO', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.CharField(default='NOINFO', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
